account_id = "YOUR_ACCOUNT_ID"
name = "protect-our-schools-pro"
main = "src/worker.mjs"
compatibility_date = "2024-11-01"
workers_dev = false

[vars]
TURNSTILE_SITEKEY = "<public-site-key>"
ALLOW_ORIGINS = "https://www.donewaiting.us,https://donewaiting.us"

# secrets: set via CLI, do NOT keep in this file:
# npx wrangler secret put TURNSTILE_SECRET

[[d1_databases]]
binding = "DB"
database_name = "protect_our_schools"
database_id = "e1cc739b-013e-4dd7-a5b5-e899becbd1b5"

[[r2_buckets]]
binding = "ARCHIVE"
bucket_name = "protect-our-schools-archive"

[durable_objects]
bindings = [
  { name = "RATELIMITER", class_name = "RateLimiter" }
]

[[migrations]]
tag = "v1-rate-limiter-sqlite-2025-08-30"
new_sqlite_classes = ["RateLimiter"]

# production route
routes = [
  { pattern = "api.donewaiting.us/*", custom_domain = true }
]
